version: "3.8"

services:
  redis:
    image: redis:7.4.2-alpine
    restart: always
    volumes:
      - ./base/redis_data:/data:rw
    ports:
      - "6379:6379"
    command: redis-server

  app:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      - CBS_REDIS_HOST=redis
      - CBS_REDIS_PORT=6379
      - CBS_BASEDIR=/base
      - CBS_LOG_LEVEL=INFO
      - CBS_ENABLE_INBUILT_BUILDER=0
      - PYTHONPATH=/app
      - GUNICORN_CMD_ARGS="--bind=0.0.0.0:8080"
    volumes:
      - ./base:/base:rw
    depends_on:
      - redis
    ports:
      - "8080:8080"

  builder:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    restart: always
    environment:
      - CBS_REDIS_HOST=redis
      - CBS_REDIS_PORT=6379
      - CBS_BASEDIR=/base
      - CBS_LOG_LEVEL=INFO
      - PYTHONPATH=/app
    volumes:
      - ./base:/base:rw
    depends_on:
      - redis
